#!/bin/bash
# just create a short cut to this bad boy here 
# touchpad_id=`xinput list --id-only "ELAN06D4:00 04F3:32B5 Touchpad"`
touchpad_id=`xinput list | grep Touch | awk -F'id=' '{print $2}' | awk -F\  '{print $1}'`


#[01] searches for 0 or 1, $ will take first result for some reason...
state=$(xinput list-props "$touchpad_id" | grep "Device Enabled" | grep -o "[01]$")
if [ $state == '1' ];then
    xinput --disable "$touchpad_id"
else
    xinput --enable "$touchpad_id"
fi


